### ISSUE TITLE
Deadlock when Commit from a function called from JS

### ISSUE THREAD

**Issue by fiscafacile** [paralin/go-indexeddb#2]
With Go 1.17, when in a function exported to JS and called from JS the Commit result in a Deadlock :

- Go Source :
```go
var fileObjStore *indexeddb.Kvtx

func main() {
	c := make(chan struct{}, 0)
	initFileDB()
	println("Go WebAssembly Initialized")
	js.Global().Set("useFile", js.FuncOf(useFile))
	<-c
}

func initFileDB() {
	ctx := context.Background()
	// increment ver when you want to change the db structure
	ver := 1
	id := "files"
	db, err := indexeddb.GlobalIndexedDB().Open(
		ctx,
		"wasm-db",
		ver,
		func(d *indexeddb.DatabaseUpdate, oldVersion, newVersion int) error {
			if !d.ContainsObjectStore(id) {
				if err := d.CreateObjectStore(id, nil); err != nil {
					return err
				}
			}
			return nil
		},
	)
	if err == nil {
		durTx, err := indexeddb.NewDurableTransaction(db, []string{id}, indexeddb.READWRITE)
		if err == nil {
			fileObjStore, _ = indexeddb.NewKvtxTx(durTx, id)
		}
	}
	test() // this one success
}

func test() {
	if fileObjStore != nil {
		key := []byte("key")
		value := []byte("value")
		if err := fileObjStore.Set(key, value); err == nil {
			fileObjStore.Commit()
		}
	}
}

func useFile(this js.Value, args []js.Value) interface{} {
	test() // this one fail
	return
}
```

- Error in browser console :
```console
fatal error: all goroutines are asleep - deadlock!
wasm_exec.js:53 
wasm_exec.js:53 goroutine 1 [chan receive]:
wasm_exec.js:53 main.main()
wasm_exec.js:53 	main.go:20 +0x10
wasm_exec.js:53 
wasm_exec.js:53 goroutine 6 [chan receive]:
wasm_exec.js:53 github.com/paralin/go-indexeddb.WaitRequest({{}, 0x7ff800010000002b, 0x410360})
wasm_exec.js:53 	github.com/paralin/go-indexeddb@v1.0.1/request.go:36 +0x1b
wasm_exec.js:53 github.com/paralin/go-indexeddb.(*ObjectStore).Put(0x40e690, {0x2f540, 0x40e600}, {0x2f540, 0x40e620})
wasm_exec.js:53 	github.com/paralin/go-indexeddb@v1.0.1/object-store.go:28 +0x19
wasm_exec.js:53 github.com/paralin/go-indexeddb.(*DurableObjectStore).Put.func1(0x40e690)
wasm_exec.js:53 	github.com/paralin/go-indexeddb@v1.0.1/durable.go:228 +0x2
wasm_exec.js:53 github.com/paralin/go-indexeddb.(*DurableTransaction).restartTransaction(0x438100)
wasm_exec.js:53 	github.com/paralin/go-indexeddb@v1.0.1/durable.go:76 +0x2a
wasm_exec.js:53 github.com/paralin/go-indexeddb.(*DurableTransaction).Commit(0x438100)
wasm_exec.js:53 	github.com/paralin/go-indexeddb@v1.0.1/durable.go:117 +0x8
wasm_exec.js:53 github.com/paralin/go-indexeddb.(*Kvtx).Commit(...)
wasm_exec.js:53 	github.com/paralin/go-indexeddb@v1.0.1/kvtx.go:134
```

**Comment by paralin** [comment]
@fiscafacile Thanks for the report, sorry I only just saw this.

In general  when you call into Go from Js you should start another goroutine - "go test()" - and not block. use a callback function with the result if the operation blocks.

Hopefully this helps. Feel free to let me know if not.
